# Generated by Django 2.2.8 on 2020-10-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(blank=True, choices=[('', ''), ('Native', 'Native'), ('Fluent', 'Fluent'), ('Intermediate', 'Intermediate'), ('Basic', 'Basic')], max_length=200),
        ),
        migrations.AlterField(
            model_name='me',
            name='cv_style',
            field=models.CharField(choices=[('styles.css', 'Blue'), ('styles-2.css', 'Green-Blue'), ('styles-3.css', 'Green'), ('styles-4.css', 'Purple'), ('styles-5.css', 'Orange'), ('styles-6.css', 'Dark-Blue')], default='styles.css', max_length=200),
        ),
    ]
