# Generated by Django 2.2.8 on 2020-10-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20201011_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactref',
            name='me_ref',
            field=models.ForeignKey(on_delete=True, related_name='contact_refs', to='cv.Me'),
        ),
        migrations.AlterField(
            model_name='education',
            name='me_ref',
            field=models.ForeignKey(on_delete=True, related_name='educations', to='cv.Me'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='me_ref',
            field=models.ForeignKey(on_delete=True, related_name='experiences', to='cv.Me'),
        ),
        migrations.AlterField(
            model_name='extrasection',
            name='me_ref',
            field=models.ForeignKey(on_delete=True, related_name='extra_sections', to='cv.Me'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='me_ref',
            field=models.ForeignKey(on_delete=True, related_name='interests', to='cv.Me'),
        ),
        migrations.AlterField(
            model_name='language',
            name='me_ref',
            field=models.ForeignKey(on_delete=True, related_name='languages', to='cv.Me'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='me_ref',
            field=models.ForeignKey(on_delete=True, related_name='skills', to='cv.Me'),
        ),
    ]
